apiVersion: apps/v1
kind: Deployment
metadata:
  name: exampleapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      containers:
      - name: exampleapp
        image: eu.gcr.io/toop-232715/exampleapp
        ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: exampleapp
spec:
  selector:
    app: exampleapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
